{application,mcache,
             [{description,"My mcache app"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{mcache_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[mc_mcache_server,mc_mcache_storage,mcache_app,
                        mcache_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
